apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      initContainers:
        - name: demo-init
          image: groundnuty/k8s-wait-for:v1.5.1
          imagePullPolicy: Always
          args:
            - job
            - kustomize-job-5 # versioned like the image
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: demo
        ports:
        - containerPort: 80
