apiVersion: batch/v1
kind: Job
metadata:
  name: job-1
spec:
  template:
    spec:
      containers:
        - image: docker.io/dotnetroundhouse/roundhouse
          name: job
          args: 
            - --silent
            - --connectionstring="server=localhost;database=test;username=postgres;password=postgres"
      restartPolicy: Never
      shareProcessNamespace: true
