apiVersion: batch/v1
kind: Job
metadata:
  name: job-1
spec:
  template:
    spec:
      containers:
        - image: docker.io/dotnetroundhouse/roundhouse
          name: job
          args: 
            - --servername=localhost
            - --database=test
            - --silent
            - --databasetype=postgres
            - --donotcreatedatabase
            - --warnononetimescriptchanges
      restartPolicy: Never
      shareProcessNamespace: true
