apiVersion: batch/v1
kind: Job
metadata:
  name: job-1
spec:
  template:
    spec:
      containers:
        - image: docker.io/dotnetroundhouse/roundhouse
          name: job
          args: 
            - "--cs="server=localhost;database=test;username=postgres;password=postgres""
            - "--donotcreatedatabase"
            - "--silent"
      restartPolicy: Never
      shareProcessNamespace: true
