apiVersion: batch/v1
kind: Job
metadata:
  name: job-4
spec:
  template:
    spec:
      containers:
        - image: docker.io/dotnetroundhouse/roundhouse
          name: job
          args: 
            - --cs="Server=host.minikube.internal;Database=test;Username=postgres;Password=postgres;Maximum Pool Size=24;Max Auto Prepare=256;"
            - --silent
            - --databasetype=postgres
            - --donotcreatedatabase
            - --warnononetimescriptchanges
      restartPolicy: Never
      serviceAccountName: default
      shareProcessNamespace: true
