apiVersion: batch/v1
kind: Job
metadata:
  name: job-1
spec:
  template:
    spec:
      containers:
        - image: docker.io/dotnetroundhouse/roundhouse
          name: job
          args: 
            - -c="Server=localhost;Database=test;Username=postgres;Password=postgres;Maximum Pool Size=24;Max Auto Prepare=256;"
            - --silent
            - --databasetype=postgres
            - --donotcreatedatabase
            - --warnononetimescriptchanges
      restartPolicy: Never
      shareProcessNamespace: true
